var dataset = [
[
    {
        "id":"scenario-0",
        "text":"<p>Having just turned 18, you can vote for the first time in the upcoming election. You are very active on social media, but you don’t know much about politics and you are unsure that you will even vote. If you do end up voting, it will probably be for the most likable candidate or whoever your friends are voting for. You decide to do a little research on social media about the candidates.</p>",
        "img":"../img/story-0/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You look at popular blogs. You want other people's opinions to help you come to a decision.",
        "target0":"scenario-A",
        "opt1":"You look at posts from news sources and blogs. You really want to get as much information as you can.",
        "target1":"scenario-B",
    },
    {
        "id":"scenario-A",
        "text":"<p>Hanging out with your friends the next day, you decide to bring up politics to see what their opinions are. Your friend Josh says that he is going to vote for the most popular and likable candidate. Your friend Cindy says that she is going to vote for the candidate who has the best platform and policies.</p>",
        "img":"../img/story-0/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"Agree with Josh to vote for the candidate who is the most popular. After all, they are popular for a reason so they must be the best choice.",
        "target0":"scenario-A-1",
        "opt1":"You consider what Cindy is saying and decide to do a little more research for yourself.",
        "target1":"scenario-A-2",
    },
    {
        "id":"scenario-B",
        "text":"<p>After reading about this one candidate you decide to ask your friends Josh and Cindy what they think. Josh says that all that information on the candidate is true and that he is definitely going to be voting for him. CIndy says that you shouldn't get your information from social media blogs.</p>",
        "img":"../img/story-0/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You’ve been friends with Josh for longer and so he probably knows what he’s talking about.",
        "target0":"scenario-A-1",
        "opt1":"You decide to check out some other websites and social media pages. Maybe Cindy has a point.",
        "target1":"scenario-B-2",
    },
    {
        "id":"scenario-B-2",
        "text":"<p>You decide to not just look on social media for information and you start reading more articles critiquing your candidate. You realize that you don’t agree with some of the candidate's points.</p>",
        "img":"../img/story-0/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You feel confused and overwhelmed. There are just so many opinions and so much information out there. You don’t know what to think, so you probably won’t vote.",
        "target0":"scenario-B-2-1",
        "opt1":"You decide to sign up for a fact-checking webinar. After all, you want to be an educated voter and it will really help you sort out truthful information.",
        "target1":"scenario-B-2-2",
    },





    {
        "id":"scenario-A-1",
        "text":"<p>After agreeing with Josh, you decide to join more social media groups dedicated to the popular candidate. You decide to share some of the articles that he found on the page. Without fully reading the articles, you share them. You get a message for Cindy telling you that the articles you are sharing are misinformation and the real story has already been published on reputable news channels. What do you do?</p>",
        "img":"../img/story-0/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You double down on your beliefs and argue your point.",
        "target0":"scenario-A-1-1",
        "opt1":"You decide to check out if she is right, but you leave the posts up. You’re not going to just blindly listen to whatever Cindy says.",
        "target1":"scenario-A-2",
    },
    {
        "id":"scenario-A-2",
        "text":"<p>You decide to look at a few more pages to see if maybe there is information that you might be missing.</p>",
        "img":"../img/story-0/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You see even more pages that support your candidate. You think you are in the clear because everything that comes up is positive.",
        "target0":"scenario-A-1-1",
        "opt1":"You decide to not just look on social media for information and you start reading more articles critiquing your candidate. You realize that you don’t agree with some of the candidate's points.",
        "target1":"scenario-A-2-2",
    },
    {
        "id":"scenario-A-1-1",
        "text":"<p>You and Cindy fight and it gets personal. She decides that she can no longer be friends with you.</p>",
        "img":"../img/story-0/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You decide that it's probably for the best that you two are no longer friends. After all, who is she to tell you that your beliefs are wrong? Plus you only really want to be friends with people who have the same political opinions as you.",
        "target0":"scenario-A-1-1-1",
        "opt1":"You realize that maybe Cindy has a point. After all, there are some points that supporters of the candidate make that you don’t really agree with. ",
        "target1":"scenario-A-1-1-2",
    },
    {
        "id":"scenario-end",
        "text":"<p></p>",
        "endLinks":[
            "<a href='https://www.vox.com/recode/2020/4/17/21221692/digital-black-market-covid-19-coronavirus-instagram-twitter-ebay' target='_blank'>Coronavirus scammers are flooding social media with fake cures and tests</a>",
            "<a href='https://www.aljazeera.com/news/2020/4/27/iran-over-700-dead-after-drinking-alcohol-to-cure-coronavirus' target='_blank'>Iran: Over 700 dead after drinking alcohol to cure coronavirus</a>",
            "<a href='https://www.theguardian.com/world/2020/mar/24/coronavirus-cure-kills-man-after-trump-touts-chloroquine-phosphate' target='_blank'>Arizona man dies after attempting to take Trump coronavirus 'cure'</a>",
            "<a href='https://www.thestar.com.my/news/nation/2020/03/20/health-minister039s-039warm-water-method039-to-kill-coronavirus-questioned' target='_blank'>Health Minister's 'warm water method' to kill coronavirus questioned</a>",
            "<a href='https://www.straitstimes.com/asia/se-asia/baseless-covid-19-cure-alls-rampant-in-malaysia-despite-authorities-warning' target='_blank'>Baseless Covid-19 cure-alls rampant in Malaysia despite authorities' warning</a>",
            "<a href='https://www.dw.com/en/indonesia-coronavirus-herbal-remedies/a-54816957' target='_blank'>Indonesia's false coronavirus 'cures' draw concern from scientists</a>",
            "<a href='https://hongkongfp.com/2020/03/13/complete-scam-anti-virus-shut-necklaces-sold-across-hong-kong-despite-bans-around-asia/' target='_blank'>‘Complete scam’: Anti-virus ‘Shut Out’ necklaces sold across Hong Kong despite bans around Asia</a>",
            "<a href='https://www.buzzfeednews.com/article/craigsilverman/facebook-mask-ads-ban-zestads-coronavirus' target='_blank'>Facebook Banned Mask Ads. They're Still Running.</a>",
        ]
    }
],
[
    {
        "id":"scenario-0",
        "text":"<p>You are a member of a fan social media group for your favorite KPOP group. One day, you log into your account and see that someone has posted slightly political content. You ignore it at first, but it is clear that this is no longer a fan page for your favorite KPOP group, but it is now a propaganda page for a presidential candidate. You are uncomfortable with the group getting political, but you are also uncomfortable about leaving because you have made good friends through the group and this might all be temporary. What do you do?</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You stay in the group and don't say anything. After all, this should just be temporary and eventually the group admins will remove whoever is posting the political content.",
        "target0":"scenario-A",
        "opt1":"You stay in the group, but message the group admin to tell them that this is not the content you want in the group.",
        "target1":"scenario-B",
    },
    {
        "id":"scenario-A",
        "text":"<p>A couple days pass and you realize that the group admin has not confronted the people posting. In fact, the group admin has posted something politically charged as well.</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You decide not to say anything. You don't want to alienate yourself from anyone in the group, and maybe you should keep an open mind to what they are saying. After all, you don’t know too much about politics and since you all like the same KPOP group, you probably have the same political views right?",
        "target0":"scenario-A-1",
        "opt1":"You decide to reach out to some of your friends to see what they think about it. Surely they should also be uncomfortable right?",
        "target1":"scenario-A-2",
    },
    {
        "id":"scenario-B",
        "text":"<p>You decide to reach out, and you start crafting your message to the group moderator. What do you say?</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You send her a message saying that you don't feel comfortable in the group, since there is a lot of misinformation being posted and this is not the content that you signed up for.",
        "target0":"scenario-B-1",
        "opt1":"You send her a message outlining all of the posts and why they are misinformation. You express concern over group members beliefs and you feel like it is inappropriate for these posts to be allowed in the group. After all, this is supposed to be a fun group dedicated to your favorite KPOP band.",
        "target1":"scenario-B-2",
    },
    {
        "id":"scenario-A-1",
        "text":"<p>After brief research, you decide that it is not worth being left out of the group and decide not to say anything. But then, your friends start to pressure you into joining the political discussion. What do you do?</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You decide that you can’t risk losing your friends, so you share a post. There can’t be that much harm in posting. It might be disinformation but you don't think that it is a big deal.",
        "target0":"scenario-A-1-1",
        "opt1":"You say that you have just been busy and try to change the topic by bringing out the KPOP group’s new song. I mean it’s the reason you’re in the group in the first place.",
        "target1":"scenario-A-1-2",
    },
    {
        "id":"scenario-A-2",
        "text":"<p>You send a private message to a couple of  your friends in the group. You ask them if they are ok with all the political posts and whether or not they agree with them. They all send messages back saying that it's about time the group started talking about this political candidate. They are all in favor of it and they fully support the candidate.</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You are shocked! These are your friends! But maybe they have a point. After all, they are your friends and even though you only know them online, you do trust them.",
        "target0":"scenario-A-2-1",
        "opt1":"You are shocked but you think that maybe you can change their minds.",
        "target1":"scenario-A-2-2",
    },
    {
        "id":"scenario-A-2-1",
        "text":"<p>You decide to look more closely at some of the posts that were shared. What do you look for to see if what they are sharing is misinformation or not?</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You look for any spelling or grammar errors, you check out the links and you look at the source of the article.",
        "target0":"scenario-A-2-1-1",
        "opt1":"You look to see if there are any photos in the article. There’s a few photos and they look pretty legit. That's good enough. You share a post as well so you don't feel left out.",
        "target1":"scenario-A-2-1-2",
    },
    {
        "id":"scenario-A-2-2",
        "text":"<p>You care about your friends and feel like they are falling into a trap of false information. You decide to read up on the candidate to educate yourself so you can have an informed opinion. What do you look at first?</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You look at the posts that are shared in the group. You should at least understand where they are coming from.",
        "target0":"scenario-A-2-2-1",
        "opt1":"You look at the posts but then you look on some credible news sites to see if what they are posting is the same as what the news agencies are posting. You know from your own fact-checking experience that you need to check your sources, read beyond the headlines, and be aware of your own bias.",
        "target1":"scenario-A-2-2-2",
    },
    {
        "id":"scenario-B-1",
        "text":"<p>She says that she understands your point but she isn’t going to do anything about it. What do you do next?</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You do nothing. At least she has heard your concerns and can decide whether or not to do anything.",
        "target0":"scenario-B-1-1",
        "opt1":"You decide to leave the group and report the members who are spreading misinformation. You will miss the group and your friends but you can’t allow people to spread misinformation.",
        "target1":"scenario-B-1-2",
    },
    {
        "id":"scenario-B-2",
        "text":"<p>The group moderator agrees with you and agrees to and asks what you want her to do about it. What do you say?</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You don’t say anything else. She’s aware of what’s going on and she doesn’t see the need to do anything about it so you guess it’s ok",
        "target0":"scenario-B-2-1",
        "opt1":"You tell her that she should consider removing the group members causing problems. However, upon your own reflection you decide to leave the group and report the members who are spreading misinformation. You will miss the group and your friends but you can’t allow people to spread misinformation.",
        "target1":"scenario-B-2-2",
    },
    {
        "id":"scenario-B-2-2-1",
        "text":"<p>You realize that leaving the group was the best option. You decide to report the page to social media for spreading misinformation. You don’t want to be a part of the misinformation problem. You have joined a new KPOP fan page and you are loving the energy and you have made new friends who are supportive and positive. All is good.</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"The end",
        "target0":"scenario-end",
    },
    {
        "id":"scenario-A-1-1",
        "text":"<p>After you share a post, you feel like you have made a mistake. Is having KPOP friends worth getting involved in spreading misinformation? What do you do?</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You feel guilty and uncomfortable. Did you really just do that? You consider deleting it but you decide that it's not a big deal.",
        "target0":"scenario-A-1-1-1",
        "opt1":"You are uncomfortable at how people are reacting to the post and you decide to delete it.",
        "target1":"scenario-A-1-1-2",
    },
    {
        "id":"scenario-A-1-2",
        "text":"<p>You decide to try changing the subject and continue to ignore pressure from your friends, you stay in the group. Your friends begin to notice that you are not participating in the group chat as much as normal. You want to tell them that it is because you are uncomfortable with how the page has transformed into a political propaganda page.Once you tell your friends that you are uncomfortable with how the page has turned political they start turning on you and tell you that you either get on board or leave the page.</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You decide you can’t risk losing your friends so you decide to share one of the posts reluctantly.",
        "target0":"scenario-A-1-2-1",
        "opt1":"You don't want to lose your friends but you don't feel right sharing something that you dont think is truthful. You decide to tell them that you want to do more research before you post.",
        "target1":"scenario-A-1-2-2",
    },
    {
        "id":"scenario-A-1-1-2",
        "text":"<p>After you delete the post, your friends notice. They ask you about it and you tell them that you are uncomfortable engaging in the political content they were posting since you don't agree with it and you believe that it is misinformation. They take offense to that and remove you from the group. Some friends they are! However, you join a new KPOP fan club and meet some new friends. It turns out that one of your friends from the old club also felt uncomfortable and left the group. She left the group of her own will once it came out that some members were being investigated for spreading misinformation. You are glad that you deleted your post and you are happy that this new group does not pressure you to spread misinformation.</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"The end",
        "target0":"scenario-end",
    },
    {
        "id":"scenario-A-1-1-1",
        "text":"<p>Since leaving your post up, the political propaganda has escalated. It is very clear that you need to leave the group. However, you notice when you log into social media that your account has been suspended…</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":1,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"Uh oh! What happened?",
        "target0":"scenario-A-1-1-1_1",
    },
    {
        "id":"scenario-A-1-1-1_1",
        "text":"<p>Since you did not remove yourself from the group or report it, your social media account is now being investigated for violating community guidelines. You wish that you had left the group earlier. You did not believe in what they were posting, but because you didn’t speak up or remove yourself from the situation, you are being treated as if you were a part of it.</p>",
        "img":"../img/story-1/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"The end",
        "target0":"scenario-end",
    },
    {
        "id":"scenario-end",
        "text":"<p></p>",
        "endLinks":[
            "<a href='https://www.vox.com/recode/2020/4/17/21221692/digital-black-market-covid-19-coronavirus-instagram-twitter-ebay' target='_blank'>Coronavirus scammers are flooding social media with fake cures and tests</a>",
            "<a href='https://www.aljazeera.com/news/2020/4/27/iran-over-700-dead-after-drinking-alcohol-to-cure-coronavirus' target='_blank'>Iran: Over 700 dead after drinking alcohol to cure coronavirus</a>",
            "<a href='https://www.theguardian.com/world/2020/mar/24/coronavirus-cure-kills-man-after-trump-touts-chloroquine-phosphate' target='_blank'>Arizona man dies after attempting to take Trump coronavirus 'cure'</a>",
            "<a href='https://www.thestar.com.my/news/nation/2020/03/20/health-minister039s-039warm-water-method039-to-kill-coronavirus-questioned' target='_blank'>Health Minister's 'warm water method' to kill coronavirus questioned</a>",
            "<a href='https://www.straitstimes.com/asia/se-asia/baseless-covid-19-cure-alls-rampant-in-malaysia-despite-authorities-warning' target='_blank'>Baseless Covid-19 cure-alls rampant in Malaysia despite authorities' warning</a>",
            "<a href='https://www.dw.com/en/indonesia-coronavirus-herbal-remedies/a-54816957' target='_blank'>Indonesia's false coronavirus 'cures' draw concern from scientists</a>",
            "<a href='https://hongkongfp.com/2020/03/13/complete-scam-anti-virus-shut-necklaces-sold-across-hong-kong-despite-bans-around-asia/' target='_blank'>‘Complete scam’: Anti-virus ‘Shut Out’ necklaces sold across Hong Kong despite bans around Asia</a>",
            "<a href='https://www.buzzfeednews.com/article/craigsilverman/facebook-mask-ads-ban-zestads-coronavirus' target='_blank'>Facebook Banned Mask Ads. They're Still Running.</a>",
        ]
    }
],
[
    {
        "id":"scenario-0",
        "text":"<p>You are on a date with Micheal. You are having a really good conversation and are getting along. Even though this is only the second date, you two have a lot in common and they both seem to like each other. However, the conversation starts to become political and Micheal asks you what you think of the upcoming election. You say:</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"I'm not comfortable discussing politics quite yet, let's change the subject",
        "target0":"scenario-A",
        "opt1":"I’m pretty open to most of the candidates, I have to look into their platforms a little more though to be confident in my choice, but there are definitely some candidates I will not be voting for.",
        "target1":"scenario-B",
    },
    {
        "id":"scenario-B",
        "text":"<p>Micheal replies saying “Well i definitely know who I am voting for, <b>Ramon Santos</b> has my vote. The golden age of the Philippines was when <b>Santos</b> was in power, we need to get back to that.” Since you are a teacher, you know very well that this is stemming from misinformation. What do you do?</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You tell him that you don’t really agree with that. After all, you are a teacher, and you know that the information regarding that era is severely lacking and people aren’t being taught the whole truth.",
        "target0":"scenario-B-1",
        "opt1":"You decide to tell him that you know that is not true and that he's wrong for thinking that.",
        "target1":"scenario-B-2",
    },
    {
        "id":"scenario-B-1",
        "text":"<p>You notice that Micheal starts to get agitated. He fires back saying “Maybe you don’t know the whole truth! I’m from the Northern Luzon area and where I come from, the <b>Santos’s</b> are heroes!” You realize that the date is no longer going well. What do you do?</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You decide to leave. It’s better safe than sorry and you don't think that anything you say will change his mind.",
        "target0":"scenario-B-1-1",
        "opt1":"You decide to stay and finish out the date and try to change the subject.",
        "target1":"scenario-B-1-2",
    },
    {
        "id":"scenario-B-1-1",
        "text":"<p>You have decided to leave the date. You tell Micheal that you think that you should grab the bill now and split the cost. You tell him that it was nice meeting him, but unfortunately you don’t see the relationship progressing since you have drastically different views on the matter and you don’t think you can change his mind. You decide it's best not to tell him that it is because his views are entrenched in a historical distortion narrative and he is ignorant about the realities of human rights and economic abuses during the <b>Santos</b> Martial Law era. You return home and realize that a lot of people have not been taught the truth about life during the <b>Santos</b> authoritarian regime. You decide that you are going to include it in the next week’s lesson plan. You never hear from Micheal again.</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"The end",
        "target0":"scenario-end",
    },
    {
        "id":"scenario-B-2",
        "text":"<p>Micheal did not like hearing that, and your discussion escalates into an argument. He fires back saying “You don’t know what you’re talking about! You women don’t know anything.” What do you do?</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You decide that the date is over and you never want to hear or see Micheal again.",
        "target0":"scenario-B-1-1",
        "opt1":"You decide to fire back. How dare he speak to you that way. You tell him that he is ignorant for thinking that another Santos administration would be beneficial.",
        "target1":"scenario-A-1-2",
    },
    {
        "id":"scenario-A",
        "text":"<p>Micheal says “You shouldn’t be scared of talking about politics! I definitely know who I am voting for, <b>Ramon Santos</b> has my vote. The golden age of the Philippines was when <b>Santos</b> was in power, we need to get back to that!”</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You aren’t sure you agree with him, but you are open to hearing what he has to say. So you ask him why he thinks that.",
        "target0":"scenario-A-1",
        "opt1":"You tell him that you disagree. You know that the “golden age” he is referring to is just historical distortion, misinformation, and propaganda.",
        "target1":"scenario-B-1-1",
    },
    {
        "id":"scenario-A-1",
        "text":"<p>Excited to get another person on board, he says that there was no real poverty during Martial Law and that the Philippines was the richest country in Asia during the <b>Santos</b> regime. He also mentioned that it was a peaceful time without any massacres and the literacy rates have never been as high as they were during that time. What do you think?</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You think wow really! That’s pretty amazing! You can’t believe how you didn’t know all of this.",
        "target0":"scenario-A-1-1",
        "opt1":"You don’t believe him. You know that there is no way that is true.",
        "target1":"scenario-A-1-2",
    },
    {
        "id":"scenario-A-1-1",
        "text":"<p>You can’t believe that you didn’t know all of that. So you ask Micheal how he knows all of this. He says that it’s just common knowledge and everyone that he grew up with feels this way. He says that anyone who thinks differently either does not know the truth or is just lying to themselves.</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You feel bad for not knowing all of this. But he’s not bringing up any concrete facts or any official sources. Maybe what he’s saying is untrue. You should make sure to do your own research when you get home.",
        "target0":"scenario-A-1-1-1",
        "opt1":"You just keep quiet. You don't really like the way he just spoke to you. Maybe you should leave.",
        "target1":"scenario-B-1-2",
    },
    {
        "id":"scenario-A-1-2",
        "text":"<p>You know that what he is saying isn’t true. You know from your own education and knowledge from your own family that there was significant violence, the Philippines was never the richest country in Asia, and although there was an increase in poverty after the <b>Santos</b> regime, poverty was already high. You know that what is being said is misinformation. What do you do?</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You tell him that you don’t think that what he is saying is true. Although you aren’t an expert on the matter, you know that what he is saying isn’t true facts.",
        "target0":"scenario-B-1",
        "opt1":"You decide to leave. You are no longer interested in getting to know Micheal.",
        "target1":"scenario-B-1-2",
    },
    {
        "id":"scenario-B-1-2",
        "text":"<p>After you make an excuse to leave the date, you come home to see that you have a bunch of social media notifications. Micheal has posted a long rant on social media about your date and is saying horrible things about you. You decide that it is just best to report his account and block him before any real damage can be done.</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"The end",
        "target0":"scenario-end",
    },
    {
        "id":"scenario-A-1-1-1",
        "text":"<p>The date ends, and when you get home you do some research. You realize that what he was saying were common misconceptions about the <b>Santos</b> regime. When he reaches out to you to ask when you can see each other again, you tell him that you aren’t interested because you don't agree with his political views. At no fault to you, he immediately gets defensive and starts getting angry at you. What do you do?</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You decide to fight fire with fire and call him out on social media.",
        "target0":"scenario-A-1-1-1-1",
        "opt1":"You decide to write a post about the misconceptions he was talking to you about and how they are wrong. You also want to write about your experience talking with him.",
        "target1":"scenario-A-1-1-1-1",
    },
    {
        "id":"scenario-A-1-1-1-1",
        "text":"<p>You write a long post about misconceptions and disinformation surrounding the <b>Santos</b> era and about your interactions with him. He sees it and writes a long post about you, saying horrible things and posting you personal information. Soon, you start getting threats and harassment. You wish you would have reported and blocked his account when you had the chance. You now know that even though you want to help fight misinformation, the best way to do that is not over social media. Sometimes we want to educate people and tell them they are wrong when we are interacting online. Although there is space for healthy debate, sometimes it is just best to draw a line so that your wellbeing and safety isn't at <a href='https://news.abs-cbn.com/life/07/30/21/have-you-been-doxed-survey-looks-at-exposure-of-personal-data-in-online-dating' target='_blank'>risk</a>.</p>",
        "img":"../img/story-2/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"The end",
        "target0":"scenario-end",
    },
    {
        "id":"scenario-end",
        "text":"<p></p>",
        "endLinks":[
            "<a href='https://www.vox.com/recode/2020/4/17/21221692/digital-black-market-covid-19-coronavirus-instagram-twitter-ebay' target='_blank'>Coronavirus scammers are flooding social media with fake cures and tests</a>",
            "<a href='https://www.aljazeera.com/news/2020/4/27/iran-over-700-dead-after-drinking-alcohol-to-cure-coronavirus' target='_blank'>Iran: Over 700 dead after drinking alcohol to cure coronavirus</a>",
            "<a href='https://www.theguardian.com/world/2020/mar/24/coronavirus-cure-kills-man-after-trump-touts-chloroquine-phosphate' target='_blank'>Arizona man dies after attempting to take Trump coronavirus 'cure'</a>",
            "<a href='https://www.thestar.com.my/news/nation/2020/03/20/health-minister039s-039warm-water-method039-to-kill-coronavirus-questioned' target='_blank'>Health Minister's 'warm water method' to kill coronavirus questioned</a>",
            "<a href='https://www.straitstimes.com/asia/se-asia/baseless-covid-19-cure-alls-rampant-in-malaysia-despite-authorities-warning' target='_blank'>Baseless Covid-19 cure-alls rampant in Malaysia despite authorities' warning</a>",
            "<a href='https://www.dw.com/en/indonesia-coronavirus-herbal-remedies/a-54816957' target='_blank'>Indonesia's false coronavirus 'cures' draw concern from scientists</a>",
            "<a href='https://hongkongfp.com/2020/03/13/complete-scam-anti-virus-shut-necklaces-sold-across-hong-kong-despite-bans-around-asia/' target='_blank'>‘Complete scam’: Anti-virus ‘Shut Out’ necklaces sold across Hong Kong despite bans around Asia</a>",
            "<a href='https://www.buzzfeednews.com/article/craigsilverman/facebook-mask-ads-ban-zestads-coronavirus' target='_blank'>Facebook Banned Mask Ads. They're Still Running.</a>",
        ]
    }
],
[
    {
        "id":"scenario-0",
        "text":"<p>You are a travel writer. You love your job but the pandemic has made it difficult for you to find work so you have been doing freelance writing jobs. You answer an ad for a contract freelance content creator position. The hiring manager tells you that you will be making mostly social media posts and you may have to make a few fake accounts to do so. He also mentioned that you will be paid P80,000.00 per month…..and you could really use the cash…What do you do?</p>",
        "img":"../img/story-3/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You obviously take the job. You can’t afford not to.",
        "target0":"scenario-A",
        "opt1":"You take the job but you make a mental note that if it goes too far you’ll quit.",
        "target1":"scenario-A",
    },
    {
        "id":"scenario-A",
        "text":"<p>You accept the job. And the first thing they ask you to do is either make several fake social media accounts or make an article bashing the opposition. What do you do first?</p>",
        "img":"../img/story-3/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You make as many accounts as you can. Maybe if you make more than they ask you to. Maybe they'll give you a bonus?",
        "target0":"scenario-A-1",
        "opt1":"You make an article with a flashy headline accusing the opponent of accepting bribes. However, the article doesn't actually say anything about bribery.",
        "target1":"scenario-B-1",
    },
    {
        "id":"scenario-A-1",
        "text":"<p>Next, your boss wants you to use those profiles and start commenting on posts that critique a political candidate for the upcoming election. He wants you to say whatever you need to say to discredit the poster’s critiques. What do you say?</p>",
        "img":"../img/story-3/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"Accuse the poster of disinformation. You want to discredit this person as much as possible.",
        "target0":"scenario-A-1-2-1",
        "opt1":"Make an outlandish claim. That way you’re doing what you were paid to do but maybe people are less likely to believe it. That way you’re not doing much harm right?",
        "target1":"scenario-A-1-2",
    },
    {
        "id":"scenario-A-1-2",
        "text":"<p>Your posts and comments have gained traction, but not in the way that you intended. Your outlandish claims have managed to create some distrust, yes, but mostly your comments have resonated with a few individuals. These individuals start taking your claims and multiplying them. What do you do?</p>",
        "img":"../img/story-3/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You let it be. This was the point right?",
        "target0":"scenario-A-1-2-1",
        "opt1":"You feel like maybe this has gone too far… You start feeling guilty. You know you are spreading fake information and now you think it is time to back out.",
        "target1":"scenario-A-1-2-1-2",
    },
    {
        "id":"scenario-A-1-2-1",
        "text":"<p>Your boss asks you to take on a larger role. He asks you to start posting more stories accusing the opponent of being a terrorist.</p>",
        "img":"../img/story-3/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You say why not. The more money the better.",
        "target0":"scenario-A-1-2-1",
        "opt1":"You rethink your involvement in this work. You decide to decline and you tell your boss you want out.",
        "target1":"scenario-A-1-2-1-2",
    },
    {
        "id":"scenario-B-1",
        "text":"<p>Your fake article has gained a lot of popularity. It has been shared multiple times. Your boss contacts you and tells you that you’ve done a great job and he’s giving you a bonus. He says that he needs to to impersonate a government employee and create posts attacking the journalist who critiques his candidate. What do you do?</p>",
        "img":"../img/story-3/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"Impersonating a government employee seems wrong and illegal…You’re not sure that's a good idea. You seriously consider getting out of this before it’s too late. You’ve heard stories about people getting charged with cyber libel or under the cybercrimes act.",
        "target0":"scenario-B-1-1",
        "opt1":"If your boss says you won’t get into trouble then why not. But maybe you don’t want to impersonate a government employee…",
        "target1":"scenario-A-2-2",
    },
    {
        "id":"scenario-A-2-2",
        "text":"<p>You decide that you do not want to impersonate anyone online, the fake accounts were bad enough. You tell your boss and he says “Fine, but I’m going to need you to write some more fake articles.” You agree. What is your next article about?</p>",
        "img":"../img/story-3/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":1,
        "optImg":0,
        "opt0":"You start a rumor about another presidential candidate.",
        "target0":"scenario-A-1-2-1",
        "opt1":"You write an article accusing multiple news agencies and journalists of being corrupt.",
        "target1":"scenario-A-1-2-1",
    },
    {
        "id":"scenario-A-1-2-1",
        "text":"<p>Your articles have spread like wildfire and are all over social media. However, it also attracts the attention of those journalists and news agencies, as well as investigators from the social media platforms. Someone exposes your name, and now you know you are in trouble. How could this have gotten so out of hand? You resign from your job and delete all the fake accounts, posts, and articles that you made. Unfortunately, it is too late because the information is already out on the internet. You wish that you never accepted the job and you are now concerned that someone will sue you for online libel.</p>",
        "img":"../img/story-3/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"The end",
        "target0":"scenario-end",
    },
    {
        "id":"scenario-A-1-2-1-2",
        "text":"<p>You decide that you should quit this job. It is causing you too much stress to knowingly be a part of the disinformation problem. However, before you can quit, you notice that a number of your accounts have been reported for spreading misinformation. You quickly delete all the others and go dark. A month later, you haven’t heard anything from the social media sites, your boss, or the authorities, however you remain stressed and on edge about your actions. Hopefully you will be able to move on from this.</p>",
        "img":"../img/story-3/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"The end",
        "target0":"scenario-end",
    },
    {
        "id":"scenario-B-1-1",
        "text":"<p>You have decided to quit. You immediately go dark and close all the false social media accounts and try to delete as much of your content as possible. You don’t want any of this traced back to you, so that it doesn’t affect your future. You’re glad that you are not a part of the disinformation problem anymore and vow to never be a part of it again. You also make sure to share any tips and tricks for sorting out disinformation and fact-checking to whomever asks you.</p>",
        "img":"../img/story-3/placeholder-800x600.png",
        "more":0,
        "info":"",
        "optNum":0,
        "optImg":0,
        "opt0":"The end",
        "target0":"scenario-end",
    },
    {
        "id":"scenario-end",
        "text":"<p></p>",
        "endLinks":[
            "<a href='https://www.vox.com/recode/2020/4/17/21221692/digital-black-market-covid-19-coronavirus-instagram-twitter-ebay' target='_blank'>Coronavirus scammers are flooding social media with fake cures and tests</a>",
            "<a href='https://www.aljazeera.com/news/2020/4/27/iran-over-700-dead-after-drinking-alcohol-to-cure-coronavirus' target='_blank'>Iran: Over 700 dead after drinking alcohol to cure coronavirus</a>",
            "<a href='https://www.theguardian.com/world/2020/mar/24/coronavirus-cure-kills-man-after-trump-touts-chloroquine-phosphate' target='_blank'>Arizona man dies after attempting to take Trump coronavirus 'cure'</a>",
            "<a href='https://www.thestar.com.my/news/nation/2020/03/20/health-minister039s-039warm-water-method039-to-kill-coronavirus-questioned' target='_blank'>Health Minister's 'warm water method' to kill coronavirus questioned</a>",
            "<a href='https://www.straitstimes.com/asia/se-asia/baseless-covid-19-cure-alls-rampant-in-malaysia-despite-authorities-warning' target='_blank'>Baseless Covid-19 cure-alls rampant in Malaysia despite authorities' warning</a>",
            "<a href='https://www.dw.com/en/indonesia-coronavirus-herbal-remedies/a-54816957' target='_blank'>Indonesia's false coronavirus 'cures' draw concern from scientists</a>",
            "<a href='https://hongkongfp.com/2020/03/13/complete-scam-anti-virus-shut-necklaces-sold-across-hong-kong-despite-bans-around-asia/' target='_blank'>‘Complete scam’: Anti-virus ‘Shut Out’ necklaces sold across Hong Kong despite bans around Asia</a>",
            "<a href='https://www.buzzfeednews.com/article/craigsilverman/facebook-mask-ads-ban-zestads-coronavirus' target='_blank'>Facebook Banned Mask Ads. They're Still Running.</a>",
        ]
    }
]
]